export default {
  "choose-your-path": "Choose Your Path",
  "first-10-minutes": "First 10 Minutes",
  "end-to-end": "End-to-End Tutorial",
  "custom-agent": "Build a Custom Agent",
  "strategy-writing": "Writing Strategies",
  "production-readiness": "Production Readiness",
  "incident-response": "Incident Response",
  "multi-tenant-integration": "Multi-Tenant Integration",
  upgrading: "Upgrading",
  "multi-agent": "Multi-Agent Teams",
  "accept-payments": "Accept Payments",
  "go-onchain": "Go On-Chain",
  "extending": "Extending the Framework",
};
