from typing import Final, Literal

from ._version import __version__
from .artifacts import LoadedArtifact, validate_artifact_directory
from .config import build_planner_factory, load_config_file
from .crypto import MockCryptoExecutionRouter
from .data_layer import (
    DataResult,
    DataRouter,
    DataSource,
    DataSourceCost,
    HTTPDataSource,
    McpDataSource,
    MockDataSource,
    Subscription,
    WebSocketDataSource,
    X402DataSource,
)
from .evals import build_promotion_evidence, evaluate_scenario_pack
from .exceptions import (
    ConfigError,
    CryptoError,
    ForgeError,
    PolicyDeniedError,
    PolicyError,
    ProviderError,
    SecurityError,
    ValidationError,
)
from .facade import Forge, ForgeProject
from .generator import FastGenerateRequest, GeneratedArtifactSet, generate_fast_artifact_set
from .http import HttpError, RetryPolicy, http_get_json, http_post_json
from .market_data import (
    BinanceVenue,
    CoinGeckoVenue,
    MarketDataRouter,
    MarketDataVenue,
    MockVenue,
    build_market_data_router,
)
from .memory import (
    InMemoryMemoryStore,
    MemoryPromotionPolicy,
    MemoryPromotionRequest,
    MemoryPromotionResult,
    MemoryQuery,
    MemoryRecord,
    MemoryStore,
)
from .models import (
    AnthropicPlanningModel,
    GeminiPlanningModel,
    OpenAICompatiblePlanningModel,
    StaticPlanningModel,
)
from .observability import (
    CompositeEventSink,
    EventSink,
    JsonlEventSink,
    ListEventSink,
    LoggingEventSink,
    ObservabilityEvent,
)
from .planner import HeuristicPlanner, PlanningModel, PromptDrivenPlanner
from .policy import NativePolicyGate, PolicyDecision
from .runner import AgentRunner, RunnerConfig
from .runtime import (
    ArtifactBundle,
    ExecutionResult,
    ExecutionRouter,
    Planner,
    RuntimeReplay,
    RuntimeSession,
    StepLedgerEntry,
    StepProposal,
)
from .scaffold_router import StrategyConfig, load_scaffold_router
from .secrets import (
    ChainSecretsProvider,
    EnvSecretsProvider,
    FileSecretsProvider,
    SecretsProvider,
    build_secrets_provider,
)
from .skills import InstalledSkill, SkillInfo, install_skill_to_project, search_skills
from .slow_generate import SlowGenerateRequest, SlowGenerateResult, generate_slow_artifact_set
from .storage import MemoryEncryption, SqliteMemoryStore
from .usage import TokenUsage, UsageTracker, estimate_session_cost
from .versioning import SemanticVersion, assess_artifact_set_compatibility
from .x402_client import HaltedError, PaymentBudgetError, PaymentRequirement, X402Client, X402Config, X402Error

_ApiStability = Literal["stable", "experimental", "internal"]

__all__ = [
    "__version__",
    "API_STABILITY",
    "Forge",
    "ForgeProject",
    "ObservabilityEvent",
    "EventSink",
    "ListEventSink",
    "LoggingEventSink",
    "JsonlEventSink",
    "CompositeEventSink",
    # Extension Protocols (build your own planner / router / memory / data source)
    "Planner",
    "ExecutionRouter",
    "PlanningModel",
    "MemoryStore",
    "DataSource",
    "Subscription",
    # Runtime
    "RuntimeSession",
    "ArtifactBundle",
    "StepProposal",
    "ExecutionResult",
    "StepLedgerEntry",
    "RuntimeReplay",
    "NativePolicyGate",
    "PolicyDecision",
    "HeuristicPlanner",
    "PromptDrivenPlanner",
    "MemoryRecord",
    "MemoryQuery",
    "MemoryPromotionRequest",
    "MemoryPromotionResult",
    "InMemoryMemoryStore",
    "MemoryPromotionPolicy",
    "validate_artifact_directory",
    "LoadedArtifact",
    "evaluate_scenario_pack",
    "build_promotion_evidence",
    "generate_fast_artifact_set",
    "FastGenerateRequest",
    "GeneratedArtifactSet",
    "assess_artifact_set_compatibility",
    "SemanticVersion",
    "MockCryptoExecutionRouter",
    "load_config_file",
    "build_planner_factory",
    "generate_slow_artifact_set",
    "SlowGenerateResult",
    "SlowGenerateRequest",
    "search_skills",
    "install_skill_to_project",
    "SkillInfo",
    "InstalledSkill",
    "SqliteMemoryStore",
    "AnthropicPlanningModel",
    "GeminiPlanningModel",
    "OpenAICompatiblePlanningModel",
    "StaticPlanningModel",
    "SecretsProvider",
    "EnvSecretsProvider",
    "FileSecretsProvider",
    "ChainSecretsProvider",
    "build_secrets_provider",
    "MarketDataVenue",
    "MarketDataRouter",
    "BinanceVenue",
    "CoinGeckoVenue",
    "MockVenue",
    "build_market_data_router",
    # Data layer (DataSource implementations + router + supporting types)
    "DataResult",
    "DataRouter",
    "DataSourceCost",
    "HTTPDataSource",
    "X402DataSource",
    "WebSocketDataSource",
    "McpDataSource",
    "MockDataSource",
    "ForgeError",
    "ValidationError",
    "PolicyError",
    "PolicyDeniedError",
    "CryptoError",
    "SecurityError",
    "ProviderError",
    "ConfigError",
    "http_get_json",
    "http_post_json",
    "RetryPolicy",
    "HttpError",
    "TokenUsage",
    "UsageTracker",
    "estimate_session_cost",
    "MemoryEncryption",
    "AgentRunner",
    "RunnerConfig",
    "StrategyConfig",
    "load_scaffold_router",
    "X402Client",
    "X402Config",
    "X402Error",
    "PaymentBudgetError",
    "HaltedError",
    "PaymentRequirement",
]

API_STABILITY: Final[dict[str, _ApiStability]] = {
    "__version__": "stable",
    "API_STABILITY": "stable",
    "Forge": "stable",
    "ForgeProject": "stable",
    "ObservabilityEvent": "experimental",
    "EventSink": "experimental",
    "ListEventSink": "experimental",
    "LoggingEventSink": "experimental",
    "JsonlEventSink": "experimental",
    "CompositeEventSink": "experimental",
    "Planner": "stable",
    "ExecutionRouter": "stable",
    "PlanningModel": "stable",
    "MemoryStore": "stable",
    "DataSource": "stable",
    "Subscription": "stable",
    "RuntimeSession": "stable",
    "ArtifactBundle": "stable",
    "StepProposal": "stable",
    "ExecutionResult": "stable",
    "StepLedgerEntry": "stable",
    "RuntimeReplay": "stable",
    "NativePolicyGate": "stable",
    "PolicyDecision": "stable",
    "HeuristicPlanner": "stable",
    "PromptDrivenPlanner": "stable",
    "MemoryRecord": "stable",
    "MemoryQuery": "stable",
    "MemoryPromotionRequest": "stable",
    "MemoryPromotionResult": "stable",
    "InMemoryMemoryStore": "stable",
    "MemoryPromotionPolicy": "stable",
    "validate_artifact_directory": "stable",
    "LoadedArtifact": "stable",
    "evaluate_scenario_pack": "stable",
    "build_promotion_evidence": "stable",
    "generate_fast_artifact_set": "stable",
    "FastGenerateRequest": "stable",
    "GeneratedArtifactSet": "stable",
    "assess_artifact_set_compatibility": "stable",
    "SemanticVersion": "stable",
    "MockCryptoExecutionRouter": "stable",
    "load_config_file": "stable",
    "build_planner_factory": "stable",
    "SqliteMemoryStore": "stable",
    "AnthropicPlanningModel": "stable",
    "GeminiPlanningModel": "stable",
    "OpenAICompatiblePlanningModel": "stable",
    "StaticPlanningModel": "stable",
    "SecretsProvider": "stable",
    "EnvSecretsProvider": "stable",
    "FileSecretsProvider": "stable",
    "ChainSecretsProvider": "stable",
    "build_secrets_provider": "stable",
    "DataResult": "stable",
    "DataRouter": "stable",
    "DataSourceCost": "stable",
    "HTTPDataSource": "stable",
    "WebSocketDataSource": "stable",
    "McpDataSource": "stable",
    "MockDataSource": "stable",
    "ForgeError": "stable",
    "ValidationError": "stable",
    "PolicyError": "stable",
    "PolicyDeniedError": "stable",
    "CryptoError": "stable",
    "SecurityError": "stable",
    "ProviderError": "stable",
    "ConfigError": "stable",
    "AgentRunner": "stable",
    "RunnerConfig": "stable",
    "MemoryEncryption": "stable",
    "MarketDataVenue": "experimental",
    "MarketDataRouter": "experimental",
    "BinanceVenue": "experimental",
    "CoinGeckoVenue": "experimental",
    "MockVenue": "experimental",
    "build_market_data_router": "experimental",
    "generate_slow_artifact_set": "experimental",
    "SlowGenerateResult": "experimental",
    "SlowGenerateRequest": "experimental",
    "search_skills": "experimental",
    "install_skill_to_project": "experimental",
    "SkillInfo": "experimental",
    "InstalledSkill": "experimental",
    "X402Client": "experimental",
    "X402Config": "experimental",
    "X402Error": "experimental",
    "PaymentBudgetError": "experimental",
    "HaltedError": "experimental",
    "PaymentRequirement": "experimental",
    "X402DataSource": "experimental",
    "TokenUsage": "experimental",
    "UsageTracker": "experimental",
    "estimate_session_cost": "experimental",
    "http_get_json": "internal",
    "http_post_json": "internal",
    "RetryPolicy": "internal",
    "HttpError": "internal",
    "StrategyConfig": "internal",
    "load_scaffold_router": "internal",
}
