export default {
  index: "Introduction",
  "getting-started": "Getting Started",
  "---guides": { type: "separator", title: "Guides" },
  guides: "",
  "---features": { type: "separator", title: "Features" },
  features: "",
  "---examples": { type: "separator", title: "Examples" },
  examples: "",
  "---cookbook": { type: "separator", title: "Cookbook" },
  cookbook: "",
  "---reference": { type: "separator", title: "Reference" },
  reference: "",
  "---help": { type: "separator", title: "Help" },
  help: "",
};
